spring.application.name=My-auditorium-booking-backend

server.servlet.context-path = /api/v1

#database connection
spring.datasource.url =jdbc:postgresql://localhost:5432/auditoriumBooking
spring.datasource.username = postgres
spring.datasource.password = 58677
spring.datasource.driver-class-name = org.postgresql.Driver

#hibernate configuration
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format-sql = true


# JWT CONFIG
jwt.secret=lXhSUEXZ2mNTOSBoQdvThzs6rNRBPyUFYeKHRK2JdCi
jwt.expiration=86400000

logging.level.org.springframework.security=TRACE

